# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/.Xil/Vivado-8348-LAPTOP-N0SGJDBA/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.cache/wt} [current_project]
set_property parent.project_path {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo {c:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/camera_top.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/i2c_sender.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/ov7670_capture.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/ov7670_controller.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/ov7670_register.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/rgb_hls.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/sobel.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/camera_top_module.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/imports/new/clock_divider.vhd}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/debouce.v}
  {C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/new/vga.v}
}
read_ip -quiet {{C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/constrs_1/new/zedboard.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/akif2/Desktop/depo/Lisans Dersleri/bitirme/bitirme_camera/camera_verilog1/camera_verilog.srcs/constrs_1/new/zedboard.xdc}}]


synth_design -top camera_top_module -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef camera_top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file camera_top_module_utilization_synth.rpt -pb camera_top_module_utilization_synth.pb"
